# Generated by Django 5.1.15 on 2026-06-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResamSaleData',
            fields=[
                ('ticket_id', models.BigIntegerField(db_column='TicketId', primary_key=True, serialize=False)),
                ('ticket_code', models.BigIntegerField(blank=True, db_column='TicketCode', null=True)),
                ('service_id', models.BigIntegerField(blank=True, db_column='ServiceId', null=True)),
                ('sub_service_id', models.BigIntegerField(blank=True, db_column='SubServiceId', null=True)),
                ('origin_station', models.TextField(blank=True, db_column='OriginStation', null=True)),
                ('destination_station', models.TextField(blank=True, db_column='DestinationStation', null=True)),
                ('move_date', models.TextField(blank=True, db_column='MoveDate', null=True)),
                ('departure_time', models.TextField(blank=True, db_column='DepartureTime', null=True)),
                ('purchase_time', models.TextField(blank=True, db_column='PurchaseTime', null=True)),
                ('days_before_departure', models.BigIntegerField(blank=True, db_column='DaysBeforeDeparture', null=True)),
                ('hours_before_departure', models.BigIntegerField(blank=True, db_column='HoursBeforeDeparture', null=True)),
                ('seats_in_ticket', models.BigIntegerField(blank=True, db_column='SeatsInTicket', null=True)),
                ('total_price', models.BigIntegerField(blank=True, db_column='TotalPrice', null=True)),
                ('price', models.BigIntegerField(blank=True, db_column='Price', null=True)),
                ('discount_percent', models.BigIntegerField(blank=True, db_column='DiscountPercent', null=True)),
                ('create_source_type', models.BigIntegerField(blank=True, db_column='CreateSourceType', null=True)),
                ('ticket_status', models.BigIntegerField(blank=True, db_column='TicketStatus', null=True)),
            ],
            options={
                'verbose_name': 'Resam Sale Data',
                'verbose_name_plural': 'Resam Sale Data',
                'db_table': 'resamsaledata',
            },
        ),
    ]
