# Generated by Django 5.1.15 on 2026-06-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=2048, verbose_name='لینک مبدا')),
                ('short_code', models.CharField(editable=False, max_length=5, unique=True, verbose_name='لینک کوتاه')),
                ('visit_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'لینک',
                'verbose_name_plural': 'لینک\u200cها',
                'db_table': 'links',
                'ordering': ['-created_at'],
            },
        ),
    ]
