# Generated by Django 5.1.15 on 2026-05-31 13:13

import safar724.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_code', models.CharField(max_length=50)),
                ('destination_code', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=10)),
                ('json_data', models.JSONField(blank=True, default=safar724.models.empty_json)),
            ],
            options={
                'verbose_name': 'Travel',
                'verbose_name_plural': 'Travels',
                'db_table': 'travel',
            },
        ),
    ]
