# Generated by Django 5.1.15 on 2026-05-31 13:28

import django.db.models.deletion
import safar724.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safar724', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='json_data',
        ),
        migrations.CreateModel(
            name='CrawlDataTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, default=safar724.models.empty_json)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_data', to='safar724.travel')),
            ],
            options={
                'verbose_name': 'Crawl Data Travel',
                'verbose_name_plural': 'Crawl Data Travels',
                'db_table': 'crawl_data_travel',
                'ordering': ['-created_at'],
            },
        ),
    ]
