# Generated by Django 5.1.15 on 2026-05-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safar724', '0002_remove_travel_json_data_crawldatatravel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='date',
        ),
        migrations.AddField(
            model_name='crawldatatravel',
            name='date',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
