# Generated by Django 5.1.15 on 2026-06-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safar724', '0003_remove_travel_date_crawldatatravel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartAxisType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Chart Axis Type',
                'verbose_name_plural': 'Chart Axis Types',
                'db_table': 'chart_axis_type',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ChartParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=100)),
                ('persian_name', models.CharField(max_length=100)),
                ('axis_types', models.ManyToManyField(blank=True, related_name='chart_parameters', to='safar724.chartaxistype')),
            ],
            options={
                'verbose_name': 'Chart Parameter',
                'verbose_name_plural': 'Chart Parameters',
                'db_table': 'chart_parameter',
                'ordering': ['english_name'],
            },
        ),
    ]
