# Generated by Django 5.1.15 on 2026-06-02 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safar724', '0005_seed_chart_axis_types_and_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taavoni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persian_name', models.CharField(max_length=255, unique=True)),
                ('companyNameId', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تعاونی',
                'verbose_name_plural': 'تعاونی\u200cها',
                'db_table': 'taavoni',
            },
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.IntegerField()),
                ('companyPersianName', models.CharField(max_length=255)),
                ('companyNameId', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crawl_data_travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts_items', to='safar724.crawldatatravel')),
                ('taavoni', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='safar724.taavoni')),
            ],
            options={
                'verbose_name': 'کارتز',
                'verbose_name_plural': 'کارتزها',
                'db_table': 'carts',
            },
        ),
    ]
