# Generated by Django 5.1.15 on 2026-06-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safar724', '0006_taavoni_carts'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='availableSeatCount',
            field=models.IntegerField(default=0),
        ),
    ]
