# Generated by Django 5.1.15 on 2026-06-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safar724', '0007_carts_availableseatcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='capacity',
            field=models.IntegerField(default=25),
        ),
    ]
